// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protobuf/tunnel.v2.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage_Type int32

const (
	ControlMessage_UNKNOWN      ControlMessage_Type = 0
	ControlMessage_PING         ControlMessage_Type = 1
	ControlMessage_PONG         ControlMessage_Type = 2
	ControlMessage_ERROR        ControlMessage_Type = 3
	ControlMessage_BACKPRESSURE ControlMessage_Type = 4
)

// Enum value maps for ControlMessage_Type.
var (
	ControlMessage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "PING",
		2: "PONG",
		3: "ERROR",
		4: "BACKPRESSURE",
	}
	ControlMessage_Type_value = map[string]int32{
		"UNKNOWN":      0,
		"PING":         1,
		"PONG":         2,
		"ERROR":        3,
		"BACKPRESSURE": 4,
	}
)

func (x ControlMessage_Type) Enum() *ControlMessage_Type {
	p := new(ControlMessage_Type)
	*p = x
	return p
}

func (x ControlMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_tunnel_v2_proto_enumTypes[0].Descriptor()
}

func (ControlMessage_Type) Type() protoreflect.EnumType {
	return &file_protobuf_tunnel_v2_proto_enumTypes[0]
}

func (x ControlMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessage_Type.Descriptor instead.
func (ControlMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{5, 0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ConnectRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ConnectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAck) Reset() {
	*x = ConnectAck{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAck) ProtoMessage() {}

func (x *ConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAck.ProtoReflect.Descriptor instead.
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TunnelOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpen) Reset() {
	*x = TunnelOpen{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpen) ProtoMessage() {}

func (x *TunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpen.ProtoReflect.Descriptor instead.
func (*TunnelOpen) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelOpen) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelData) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TunnelData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TunnelClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClose) Reset() {
	*x = TunnelClose{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClose) ProtoMessage() {}

func (x *TunnelClose) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClose.ProtoReflect.Descriptor instead.
func (*TunnelClose) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelClose) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TunnelClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlMessage_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=tunnel.ControlMessage_Type" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{5}
}

func (x *ControlMessage) GetType() ControlMessage_Type {
	if x != nil {
		return x.Type
	}
	return ControlMessage_UNKNOWN
}

func (x *ControlMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Connect
	//	*Envelope_ConnectAck
	//	*Envelope_Open
	//	*Envelope_Data
	//	*Envelope_Close
	//	*Envelope_Control
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tunnel_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protobuf_tunnel_v2_proto_rawDescGZIP(), []int{6}
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Envelope) GetConnectAck() *ConnectAck {
	if x != nil {
		if x, ok := x.Message.(*Envelope_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *Envelope) GetOpen() *TunnelOpen {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *Envelope) GetData() *TunnelData {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Envelope) GetClose() *TunnelClose {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Envelope) GetControl() *ControlMessage {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type Envelope_ConnectAck struct {
	ConnectAck *ConnectAck `protobuf:"bytes,2,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type Envelope_Open struct {
	Open *TunnelOpen `protobuf:"bytes,3,opt,name=open,proto3,oneof"`
}

type Envelope_Data struct {
	Data *TunnelData `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type Envelope_Close struct {
	Close *TunnelClose `protobuf:"bytes,5,opt,name=close,proto3,oneof"`
}

type Envelope_Control struct {
	Control *ControlMessage `protobuf:"bytes,6,opt,name=control,proto3,oneof"`
}

func (*Envelope_Connect) isEnvelope_Message() {}

func (*Envelope_ConnectAck) isEnvelope_Message() {}

func (*Envelope_Open) isEnvelope_Message() {}

func (*Envelope_Data) isEnvelope_Message() {}

func (*Envelope_Close) isEnvelope_Message() {}

func (*Envelope_Control) isEnvelope_Message() {}

var File_protobuf_tunnel_v2_proto protoreflect.FileDescriptor

const file_protobuf_tunnel_v2_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/tunnel.v2.proto\x12\x06tunnel\"\x93\x01\n" +
	"\x0eConnectRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"Y\n" +
	"\n" +
	"ConnectAck\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"1\n" +
	"\n" +
	"TunnelOpen\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"K\n" +
	"\n" +
	"TunnelData\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"J\n" +
	"\vTunnelClose\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa1\x01\n" +
	"\x0eControlMessage\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.tunnel.ControlMessage.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"D\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x10\n" +
	"\fBACKPRESSURE\x10\x04\"\xb5\x02\n" +
	"\bEnvelope\x122\n" +
	"\aconnect\x18\x01 \x01(\v2\x16.tunnel.ConnectRequestH\x00R\aconnect\x125\n" +
	"\vconnect_ack\x18\x02 \x01(\v2\x12.tunnel.ConnectAckH\x00R\n" +
	"connectAck\x12(\n" +
	"\x04open\x18\x03 \x01(\v2\x12.tunnel.TunnelOpenH\x00R\x04open\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x12.tunnel.TunnelDataH\x00R\x04data\x12+\n" +
	"\x05close\x18\x05 \x01(\v2\x13.tunnel.TunnelCloseH\x00R\x05close\x122\n" +
	"\acontrol\x18\x06 \x01(\v2\x16.tunnel.ControlMessageH\x00R\acontrolB\t\n" +
	"\amessage2B\n" +
	"\rGatewayTunnel\x121\n" +
	"\aConnect\x12\x10.tunnel.Envelope\x1a\x10.tunnel.Envelope(\x010\x01B8Z6Purple-House/agni-tunnels/tunnel-proto/protobuf;tunnelb\x06proto3"

var (
	file_protobuf_tunnel_v2_proto_rawDescOnce sync.Once
	file_protobuf_tunnel_v2_proto_rawDescData []byte
)

func file_protobuf_tunnel_v2_proto_rawDescGZIP() []byte {
	file_protobuf_tunnel_v2_proto_rawDescOnce.Do(func() {
		file_protobuf_tunnel_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_tunnel_v2_proto_rawDesc), len(file_protobuf_tunnel_v2_proto_rawDesc)))
	})
	return file_protobuf_tunnel_v2_proto_rawDescData
}

var file_protobuf_tunnel_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_tunnel_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_tunnel_v2_proto_goTypes = []any{
	(ControlMessage_Type)(0), // 0: tunnel.ControlMessage.Type
	(*ConnectRequest)(nil),   // 1: tunnel.ConnectRequest
	(*ConnectAck)(nil),       // 2: tunnel.ConnectAck
	(*TunnelOpen)(nil),       // 3: tunnel.TunnelOpen
	(*TunnelData)(nil),       // 4: tunnel.TunnelData
	(*TunnelClose)(nil),      // 5: tunnel.TunnelClose
	(*ControlMessage)(nil),   // 6: tunnel.ControlMessage
	(*Envelope)(nil),         // 7: tunnel.Envelope
}
var file_protobuf_tunnel_v2_proto_depIdxs = []int32{
	0, // 0: tunnel.ControlMessage.type:type_name -> tunnel.ControlMessage.Type
	1, // 1: tunnel.Envelope.connect:type_name -> tunnel.ConnectRequest
	2, // 2: tunnel.Envelope.connect_ack:type_name -> tunnel.ConnectAck
	3, // 3: tunnel.Envelope.open:type_name -> tunnel.TunnelOpen
	4, // 4: tunnel.Envelope.data:type_name -> tunnel.TunnelData
	5, // 5: tunnel.Envelope.close:type_name -> tunnel.TunnelClose
	6, // 6: tunnel.Envelope.control:type_name -> tunnel.ControlMessage
	7, // 7: tunnel.GatewayTunnel.Connect:input_type -> tunnel.Envelope
	7, // 8: tunnel.GatewayTunnel.Connect:output_type -> tunnel.Envelope
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_tunnel_v2_proto_init() }
func file_protobuf_tunnel_v2_proto_init() {
	if File_protobuf_tunnel_v2_proto != nil {
		return
	}
	file_protobuf_tunnel_v2_proto_msgTypes[6].OneofWrappers = []any{
		(*Envelope_Connect)(nil),
		(*Envelope_ConnectAck)(nil),
		(*Envelope_Open)(nil),
		(*Envelope_Data)(nil),
		(*Envelope_Close)(nil),
		(*Envelope_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_tunnel_v2_proto_rawDesc), len(file_protobuf_tunnel_v2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_tunnel_v2_proto_goTypes,
		DependencyIndexes: file_protobuf_tunnel_v2_proto_depIdxs,
		EnumInfos:         file_protobuf_tunnel_v2_proto_enumTypes,
		MessageInfos:      file_protobuf_tunnel_v2_proto_msgTypes,
	}.Build()
	File_protobuf_tunnel_v2_proto = out.File
	file_protobuf_tunnel_v2_proto_goTypes = nil
	file_protobuf_tunnel_v2_proto_depIdxs = nil
}
