// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: protobuf/tunnel.v2.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayTunnel_Connect_FullMethodName = "/tunnel.GatewayTunnel/Connect"
)

// GatewayTunnelClient is the client API for GatewayTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayTunnelClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type gatewayTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayTunnelClient(cc grpc.ClientConnInterface) GatewayTunnelClient {
	return &gatewayTunnelClient{cc}
}

func (c *gatewayTunnelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayTunnel_ServiceDesc.Streams[0], GatewayTunnel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayTunnel_ConnectClient = grpc.BidiStreamingClient[Envelope, Envelope]

// GatewayTunnelServer is the server API for GatewayTunnel service.
// All implementations must embed UnimplementedGatewayTunnelServer
// for forward compatibility.
type GatewayTunnelServer interface {
	Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedGatewayTunnelServer()
}

// UnimplementedGatewayTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayTunnelServer struct{}

func (UnimplementedGatewayTunnelServer) Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGatewayTunnelServer) mustEmbedUnimplementedGatewayTunnelServer() {}
func (UnimplementedGatewayTunnelServer) testEmbeddedByValue()                       {}

// UnsafeGatewayTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayTunnelServer will
// result in compilation errors.
type UnsafeGatewayTunnelServer interface {
	mustEmbedUnimplementedGatewayTunnelServer()
}

func RegisterGatewayTunnelServer(s grpc.ServiceRegistrar, srv GatewayTunnelServer) {
	// If the following call panics, it indicates UnimplementedGatewayTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayTunnel_ServiceDesc, srv)
}

func _GatewayTunnel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayTunnelServer).Connect(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayTunnel_ConnectServer = grpc.BidiStreamingServer[Envelope, Envelope]

// GatewayTunnel_ServiceDesc is the grpc.ServiceDesc for GatewayTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.GatewayTunnel",
	HandlerType: (*GatewayTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _GatewayTunnel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/tunnel.v2.proto",
}
